In [1]:
#importing os library
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#changing the work directory
os.chdir('/Users/sushovanmandal/Documents/code/learn-gen-ai/analyticsVidhya genAI/Foundational ML Algorithams')

In [3]:
employee_data = pd.read_csv("modified_employee_turnover.csv")
employee_data.head()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0


In [4]:
employee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 no

In [6]:
employee_data['Employee_Turnover'].value_counts()

Employee_Turnover
0    678
1    672
Name: count, dtype: int64

# Splitting the dataset into train and test sets

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV, ElasticNetCV
from sklearn.metrics import classification_report, f1_score

In [8]:
X = employee_data.drop('Employee_Turnover', axis = 1)
y = employee_data['Employee_Turnover']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [12]:
# We would like to select the random_state in which the difference between the mean of y_train and y_test is minimal.
# Experiment with the values of random_state.
y_train.mean(), y_test.mean()

(np.float64(0.49947089947089945), np.float64(0.49382716049382713))

# Training and Evaluating Base Model - no regularisation

In [13]:
# Logistic regression without regularization
logistic_no_reg = LogisticRegression(penalty=None,
                                     max_iter=10000,
                                     n_jobs=-1)
logistic_no_reg.fit(X_train, y_train)

# keeping the value of max_iter as 10000, to avoid the Convergence Warning

,penalty,None
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,10000
,multi_class,'deprecated'


In [14]:
logistic_no_reg.coef_

array([[ 6.70940841,  6.935326  ,  5.6450131 ,  6.17899683,  6.543797  ,
        -0.67539868, -1.17355763, -0.18270135, -0.08910507,  0.1237272 ,
        -0.0258387 ,  0.08106228, -0.14124152,  0.30492039,  0.05995743]])

In [15]:
# Evaluate the model without regularization for train set
y_train_pred_no_reg = logistic_no_reg.predict(X_train)
f1_no_reg = f1_score(y_train, y_train_pred_no_reg)
print("F1 Score without Regularization on train set:", f1_no_reg)

F1 Score without Regularization on train set: 0.8728813559322034


In [16]:
# Evaluate the model without regularization for test data
y_test_pred_no_reg = logistic_no_reg.predict(X_test)
f1_no_reg = f1_score(y_test, y_test_pred_no_reg)
print("F1 Score without Regularization on test set:", f1_no_reg)

F1 Score without Regularization on test set: 0.8628428927680798


Suggests no overfitting as both train and test F1 scores are near to each other

# Training and Evaluating regular logistic regression

In [18]:
# Logistic regression without regularization
log_reg = LogisticRegression(
                                     max_iter=10000,
                                     n_jobs=-1)
log_reg.fit(X_train, y_train)

# keeping the value of max_iter as 10000, to avo

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,10000
,multi_class,'deprecated'


In [19]:
log_reg.coef_

array([[ 4.32042952,  4.46888302,  3.56470859,  3.85448016,  4.20352875,
        -0.39131677, -0.8023729 , -0.05064346, -0.0603483 ,  0.15115589,
         0.03422234,  0.12960066, -0.19656145,  0.26190187,  0.03551039]])

In [21]:
# Evaluate the model with regular for train set
y_train_pred = log_reg.predict(X_train)
f1 = f1_score(y_train, y_train_pred)
print("F1 Score with regular on train set:", f1)

F1 Score with regular on train set: 0.8728813559322034


In [22]:
# Evaluate the model with regular for test data
y_test_pred = log_reg.predict(X_test)
f1 = f1_score(y_test, y_test_pred)
print("F1 Score with regular on test set:", f1)

F1 Score with regular on test set: 0.8571428571428571


Better test performance by no regularisation model with same train F1 score.

# Apply Logistic Regression with L1 Regularization 

In [23]:
# Defining a range for Cs
Cs = np.linspace(0.001,10,20)

In [24]:
# Logistic regression with L1 regularization using cross-validation to find the best C
logistic_l1_cv = LogisticRegressionCV(Cs=Cs, 
                                      penalty='l1', 
                                      solver='liblinear', 
                                      cv=5,
                                      max_iter=10000,
                                      scoring = 'f1',
                                      n_jobs=-1)
logistic_l1_cv.fit(X_train, y_train)

,Cs,array([1.0000...00000000e+01])
,fit_intercept,True
,cv,5
,dual,False
,penalty,'l1'
,scoring,'f1'
,solver,'liblinear'
,tol,0.0001
,max_iter,10000
,class_weight,None
,n_jobs,-1


In [25]:
logistic_l1_cv.Cs

array([1.00000000e-03, 5.27263158e-01, 1.05352632e+00, 1.57978947e+00,
       2.10605263e+00, 2.63231579e+00, 3.15857895e+00, 3.68484211e+00,
       4.21110526e+00, 4.73736842e+00, 5.26363158e+00, 5.78989474e+00,
       6.31615789e+00, 6.84242105e+00, 7.36868421e+00, 7.89494737e+00,
       8.42121053e+00, 8.94747368e+00, 9.47373684e+00, 1.00000000e+01])

In [26]:
best_C = logistic_l1_cv.C_
print(f"The best Cs value is: {best_C}")

The best Cs value is: [0.52726316]


In [27]:
# Evaluate the model with L1 regularization on train set
y_train_pred_l1 = logistic_l1_cv.predict(X_train)
f1_l1 = f1_score(y_train, y_train_pred_l1)
print("F1 Score with L1 Regularization on train set:", f1_l1)

F1 Score with L1 Regularization on train set: 0.8734177215189873


In [28]:
# Evaluate the model with L1 regularization on test set
y_test_pred_l1 = logistic_l1_cv.predict(X_test)
f1_l1 = f1_score(y_test, y_test_pred_l1)
print("F1 Score with L1 Regularization on test set:", f1_l1)

F1 Score with L1 Regularization on test set: 0.8684863523573201


In [30]:
coefficients_after_l1 = pd.DataFrame({
    'Feature': X_train.columns,
    'After L1 Regularization': logistic_l1_cv.coef_.flatten()
})
print(coefficients_after_l1.sort_values(by = 'After L1 Regularization' ))

                                    Feature  After L1 Regularization
6                           Education_Level                -0.831681
5                            Monthly_Income                -0.385099
12                               Department                -0.072715
7                                       Age                 0.000000
8                      Num_Companies_Worked                 0.000000
9                             Employee_Role                 0.000000
10                             Annual_Bonus                 0.000000
11                           Training_Hours                 0.000000
14  Annual_Bonus_Training_Hours_Interaction                 0.000000
13                     Annual_Bonus_Squared                 0.046795
2                          Years_At_Company                 3.954305
3                         Work_Life_Balance                 4.325319
4                        Distance_From_Home                 4.713015
0                          Job_Sat

In [31]:
# Identify zero features from logisitc regression L1 model
zero_mask = (logistic_l1_cv.coef_ == 0).flatten()
zero_features = X_train.columns[zero_mask]
# Print the features with zero coefficients 
zero_features.tolist()

['Age',
 'Num_Companies_Worked',
 'Employee_Role',
 'Annual_Bonus',
 'Training_Hours',
 'Annual_Bonus_Training_Hours_Interaction']

L1 regularisation is giving the best train and test f1 scores.

# Apply Logistic Regression with L2 Regularization 


In [32]:
# Defining a range for Cs 
Cs= np.linspace(0.001,10,20)

In [33]:
# Logistic regression with L2 regularization using cross-validation to find the best C
logistic_l2_cv = LogisticRegressionCV(Cs=Cs, 
                                      penalty='l2', 
                                      solver='liblinear',
                                      cv=5, 
                                      max_iter=10000,
                                      n_jobs=-1)
logistic_l2_cv.fit(X_train, y_train)

,Cs,array([1.0000...00000000e+01])
,fit_intercept,True
,cv,5
,dual,False
,penalty,'l2'
,scoring,None
,solver,'liblinear'
,tol,0.0001
,max_iter,10000
,class_weight,None
,n_jobs,-1


In [34]:
logistic_l2_cv.Cs_

array([1.00000000e-03, 5.27263158e-01, 1.05352632e+00, 1.57978947e+00,
       2.10605263e+00, 2.63231579e+00, 3.15857895e+00, 3.68484211e+00,
       4.21110526e+00, 4.73736842e+00, 5.26363158e+00, 5.78989474e+00,
       6.31615789e+00, 6.84242105e+00, 7.36868421e+00, 7.89494737e+00,
       8.42121053e+00, 8.94747368e+00, 9.47373684e+00, 1.00000000e+01])

In [35]:
best_C = logistic_l2_cv.C_
print(f"The best Cs value is: {best_C}")

The best Cs value is: [3.68484211]


In [36]:
# Evaluate the model with L2 regularization on train data
y_train_pred_l2 = logistic_l2_cv.predict(X_train)
f1_l2 = f1_score(y_train, y_train_pred_l2)
print("F1 Score with L2 Regularization on train data:", f1_l2)

F1 Score with L2 Regularization on train data: 0.8673684210526316


In [37]:
# Evaluate the model with L2 regularization on test data
y_test_pred_l2 = logistic_l2_cv.predict(X_test)
f1_l2 = f1_score(y_test, y_test_pred_l2)
print("F1 Score with L2 Regularization on test data:", f1_l2)

F1 Score with L2 Regularization on test data: 0.8635235732009926


In [38]:
coefficients_after_l2 = pd.DataFrame({
    'Feature': X_train.columns,
    'After L2 Regularization': logistic_l2_cv.coef_.flatten()
})
print(coefficients_after_l2.sort_values(by = 'After L2 Regularization' ))

                                    Feature  After L2 Regularization
6                           Education_Level                -1.079810
10                             Annual_Bonus                -0.679916
5                            Monthly_Income                -0.650496
12                               Department                -0.360414
11                           Training_Hours                -0.329267
7                                       Age                -0.242951
8                      Num_Companies_Worked                -0.202649
9                             Employee_Role                 0.000120
13                     Annual_Bonus_Squared                 0.553524
14  Annual_Bonus_Training_Hours_Interaction                 0.620303
2                          Years_At_Company                 4.116569
3                         Work_Life_Balance                 4.494947
4                        Distance_From_Home                 4.849658
0                          Job_Sat

# Elastic Net

In [39]:
Cs=np.linspace(0.001,10,20)

In [40]:
# Logistic regression with Elastic Net regularization using cross-validation
logistic_en_cv = LogisticRegressionCV(penalty='elasticnet',
                                      Cs = Cs,
                                      l1_ratios= [0.0001, 0.001, 0.01, 0.05, 0.1, 0.4, 0.5, 0.7, 1], 
                                      solver='saga', 
                                      cv=5,
                                      max_iter=1000000,
                                      n_jobs=-1)
logistic_en_cv.fit(X_train, y_train)

,Cs,array([1.0000...00000000e+01])
,fit_intercept,True
,cv,5
,dual,False
,penalty,'elasticnet'
,scoring,None
,solver,'saga'
,tol,0.0001
,max_iter,1000000
,class_weight,None
,n_jobs,-1


In [41]:
logistic_en_cv.C_

array([0.52726316])

In [42]:
logistic_en_cv.l1_ratio_

array([0.7])

In [43]:
# Evaluate the model
y_train_pred_elastic = logistic_en_cv.predict(X_train)
f1_elastic_train = f1_score(y_train, y_train_pred_elastic)
print("F1 Score with Elastic Net Regularization on Train Set:", f1_elastic_train)

F1 Score with Elastic Net Regularization on Train Set: 0.8710359408033826


In [44]:
y_test_pred_elastic = logistic_en_cv.predict(X_test)
f1_elastic_test = f1_score(y_test, y_test_pred_elastic)
print("F1 Score with Elastic Net Regularization on Test Set:", f1_elastic_test)

F1 Score with Elastic Net Regularization on Test Set: 0.86


## With L1 regularisation the best train and test scores come