# Import the libraries

In [1]:
#Import the torch library followed by torch.nn library as nn
import torch
import torch.nn as nn

# Assign inputs to the neuron

In [2]:
#Inputs to the neuron (Note: We have used random values here) 
inputs = torch.tensor ([3.0,2.0,-1.0])

In [3]:
#Create a neuron with 3 features and 1 output
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(inputs)

# Print the output

In [4]:
#Print the final output of the neuron
print (output)

tensor([1.0152], grad_fn=<ViewBackward0>)


# Weight of the neuron

In [5]:
#To view the weight of the neuron
neuron.weight

Parameter containing:
tensor([[ 0.2066, -0.2766, -0.5577]], requires_grad=True)

# Bias of the neuron

In [6]:
#To view the bias of the neuron
neuron.bias

Parameter containing:
tensor([0.3908], requires_grad=True)

# Mathematical Formula:

In [8]:
#Formula for the final output of the neuron
neuron.weight@inputs.T + neuron.bias

tensor([1.0152], grad_fn=<AddBackward0>)